<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VersionPrefix>1.2</VersionPrefix>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyVersion>1.2.1.1</AssemblyVersion>
    <FileVersion>1.2.1.1</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Crypto\**" />
    <Compile Remove="Resources\**" />
    <EmbeddedResource Remove="Crypto\**" />
    <EmbeddedResource Remove="Resources\**" />
    <None Remove="Crypto\**" />
    <None Remove="Resources\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Data\TimeZones.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data\TimeZones.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" />
    <PackageReference Include="LagoVista.Core.Authentication" />
    <PackageReference Include="LagoVista.Core.Rpc" />
    <PackageReference Include="LagoVista.Core.Rpc.Client" />
    <PackageReference Include="LagoVista.IoT.DeviceAdmin" />
    <PackageReference Include="LagoVista.IoT.DeviceManagement.Core" />
    <PackageReference Include="LagoVista.IoT.DeviceMessaging.Admin" />
    <PackageReference Include="LagoVista.IoT.Pipeline.Admin" />
    <PackageReference Include="prometheus-net" />
    <PackageReference Include="LagoVista.UserAdmin" />
    <PackageReference Include="Portable.BouncyCastle" />
    <PackageReference Include="MQTTnet" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LagoVista.IoT.Deployment.Models\LagoVista.IoT.Deployment.Models.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
</Project>
