<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LagoVista.Core.Configuration" />
    <PackageReference Include="LagoVista.CloudStorage" />
    <PackageReference Include="LagoVista.IoT.Pipeline.CloudRepos" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LagoVista.IoT.Deployment.Admin\LagoVista.IoT.Deployment.Admin.csproj" />
  </ItemGroup>
</Project>
